name: 'coverage'
on:
    pull_request_target:
        branches:
            - main
    push:
        branches:
            - main
defaults:
 run:
  working-directory: ./CalculatorApp
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Install dependencies
            run: npm ci

          - name: Run tests
            run: |
             npx jest --coverage --coverageReporters json-summary

          - name: Jest Coverage Comment
            uses: MishaKav/jest-coverage-comment@main
            with: 
                  working-directory: ./CalculatorApp
